### PR TITLE
Feature/openstack network with terraform

### PR DESCRIPTION
**Pull request by andersla**

### CODE REVIEW

**Comment by mcapuccini** [comment]
@andersla it seems like the network folder is missing. Is it possible to have the ssh key created and the security group as well?

**Comment by andersla** [comment]
I had forgotten to add it:)
I'll do the keys later.

**Comment by mcapuccini** [comment]
@andersla I synched this PR with the master, you may need to pull. It misses a couple of things:

- updated version of openstack/main.yml
- updated version of terraform.tfvars.os-template
- documentation for the new parameters (security group name, and ssh key path)

Look forward to test it :)

**Comment by andersla** [comment]
fixed it!
      
      On 2016-11-02 17:41, Marco Capuccini wrote:
    
    
      @mcapuccini requested changes on this pull request.
      some files are missing
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mcapuccini/KubeNow","title":"mcapuccini/KubeNow","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mcapuccini/KubeNow"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mcapuccini requested changes on #14"}],"action":{"name":"View Pull Request","url":"https://github.com/mcapuccini/KubeNow/pull/14#pullrequestreview-6857107"}}}

**Comment by mcapuccini** [comment]
@andersla good job! It worked great!

**Pull request merged**
